name: iOS Build & TestFlight Upload

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    env:
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APP_SPECIFIC_PASSWORD: ${{ secrets.GITHUBACTIONS }}

    steps:
      - name: Set up Xcode 16.2
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Swift 6.1.0
        uses: fwal/setup-swift@v1
        with:
          swift-version: "6.1.0"

      - name: Confirm Swift Version
        run: swift --version

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install Bundler
        run: gem install bundler

      - name: Install dependencies
        run: bundle install

      - name: Run Fastlane beta lane
        run: bundle exec fastlane beta
