name: iOS Build & TestFlight Upload

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    env:
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APP_SPECIFIC_PASSWORD: ${{ secrets.GITHUBACTIONS }}

    steps:
  

      - name: Install Bundler
        run: gem install bundler

      - name: Install dependencies
        run: bundle install

      - name: Run Fastlane beta lane
        run: bundle exec fastlane beta
        
