name: iOS Build & TestFlight Upload

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    env:
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APP_SPECIFIC_PASSWORD: ${{ secrets.GITHUBACTIONS }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Disable File System Synchronized Groups (fix Xcode 15.3 assert)
        run: echo "IDEFileSystemSynchronizedGroupsEnabled=NO" >> $GITHUB_ENV

      - name: Set up Xcode 15.0
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0'

      - name: Confirm Swift version
        run: swift --version

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install Bundler
        run: gem install bundler

      - name: Install dependencies
        run: bundle install

      - name: Run Fastlane beta lane
        run: bundle exec fastlane beta
        # No need to re-specify IDEFileSystemSynchronizedGroupsEnabled here,
        # it's set globally in $GITHUB_ENV
