name: iOS Build & TestFlight Upload

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    env:
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APP_SPECIFIC_PASSWORD: ${{ secrets.GITHUBACTIONS }}
      IDEFileSystemSynchronizedGroupsEnabled: "NO"   # Disable the FS Synchronized Groups to fix Xcode assertion

    steps:
      - name: Set up Xcode 15.3
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.3'

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Confirm Swift Version
        run: swift --version

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install Bundler
        run: gem install bundler

      - name: Install dependencies
        run: bundle install

      - name: Run Fastlane beta lane
        run: bundle exec fastlane beta
